apiVersion: v1
kind: Service
metadata:
  name: stripe-clone-service
  labels:
    app: stripe-clone
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    app: stripe-clone
  sessionAffinity: None